services:
  transcription-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audio-video-transcription
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
      - SPACY_MODEL=${SPACY_MODEL:-en_core_web_sm}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-100MB}
      - TEMP_DIR=/app/temp
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
      # Speaker diarization configuration
      - ENABLE_SPEAKER_DIARIZATION=${ENABLE_SPEAKER_DIARIZATION:-true}
      - SPEAKER_DIARIZATION_MODEL=${SPEAKER_DIARIZATION_MODEL:-pyannote/speaker-diarization-3.1}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      # Redis configuration
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - model-cache:/root/.cache
      - temp-files:/app/temp
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - transcription-network
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

  redis:
    image: redis:7-alpine
    container_name: transcription-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - transcription-network
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru

  nginx:
    image: nginx:alpine
    container_name: transcription-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped
    networks:
      - transcription-network
    depends_on:
      - transcription-service

networks:
  transcription-network:
    driver: bridge

volumes:
  model-cache:
    driver: local
  temp-files:
    driver: local
  redis-data:
    driver: local
