services:
  transcription-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audio-video-transcription
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
      - SPACY_MODEL=${SPACY_MODEL:-en_core_web_sm}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-100MB}
      - TEMP_DIR=/app/temp
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
      - MAX_WORKERS=1
      # Speaker diarization configuration
      - ENABLE_SPEAKER_DIARIZATION=${ENABLE_SPEAKER_DIARIZATION:-true}
      - SPEAKER_DIARIZATION_MODEL=${SPEAKER_DIARIZATION_MODEL:-pyannote/speaker-diarization-3.1}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - ./model-cache:/root/.cache
      - ./temp-files:/app/temp
    restart: unless-stopped
    networks:
      - transcription-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  transcription-network:
    driver: bridge

volumes:
  model-cache:
    driver: local