services:
  transcription-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audio-video-transcription
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
      - SPACY_MODEL=${SPACY_MODEL:-en_core_web_sm}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-2GB}
      - TEMP_DIR=/app/temp
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
      - MAX_WORKERS=4
      - MAX_CONCURRENT_JOBS=4
      - DATABASE_PATH=/app/data/transcription_jobs.db
      - WEBHOOK_TIMEOUT=30
      - WEBHOOK_MAX_RETRIES=3
    volumes:
      - ./model-cache:/root/.cache
      - ./temp-files:/app/temp
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - transcription-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  transcription-network:
    driver: bridge

volumes:
  model-cache:
    driver: local